# Generated by Django 4.2.5 on 2024-02-11 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Manufacturer',
            new_name='manufacturer',
        ),
    ]
